name: "Build & Publish collection to Ansible Galaxy"
description: "Build & Publish collection to Ansible Galaxy"
inputs:
  galaxy_token:
    description: "Ansible galaxy token to use"
    required: true
  galaxy_server:
    description: 'Galaxy server you want to push to'
    required: false
    default: 'https://galaxy.ansible.com'
branding:
  icon: 'chevrons-right'  
  color: 'black'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.galaxy_token }}
    - ${{ inputs.galaxy_server }}
